name: Snyk Container
on: push
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - uses: hadolint/hadolint-action@v2.1.0
      with:
       dockerfile: vault/Dockerfile
       failure-threshold: error
       
    - uses: actions/checkout@v2
    - name: Build a Docker image
      run: docker build -t vault-test vault/.
      
    - name: Run Snyk to check Docker image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: vault-test
        args: --file=vault/Dockerfile
