name: Pipeline upgrade
on: push
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hadolint/hadolint-action@v2.1.0
      with:
       dockerfile: vault/Dockerfile
       failure-threshold: error
       
    - uses: actions/checkout@v3
    - name: Build a Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USER }}/vault:latest vault/.
      
    - name: Run Snyk to check Docker image for vulnerabilities
      continue-on-error: true
      id: docker-image-scan
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ${{ secrets.DOCKERHUB_USER }}/vault:latest
        args: --file=vault/Dockerfile
              --severity-threshold=high
              --sarif-file-output=./vault/docker.snyk.sarif
        sarif: false
    
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: vault
        
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKERHUB_USER }}/vault:latest
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
    
    - name: Check docker image scan status
      if: ${{ steps.docker-image-scan.outcome == 'failure' }}
      run: exit 1
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}
        
    - name: Push the docker image
      run: docker push ${{ secrets.DOCKERHUB_USER }}/vault:latest
      
    - name: Logout from Docker Hub
      run: docker logout
